// Reads compiled Foundry artifacts in ../web3/out and emits a TypeScript file
// with `as const` ABI literals so wagmi can infer types end-to-end.
//
// Run from the client directory: `bun run scripts/extract-abis.mjs` (also wired
// up as the `abis` script in package.json).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..")
const outDir = join(repoRoot, "web3", "out")
const targets = [
  { name: "factoryAbi", path: join(outDir, "IMSYMarketFactory.sol", "IMSYMarketFactory.json") },
  { name: "marketAbi", path: join(outDir, "IMSYMarket.sol", "IMSYMarket.json") },
  { name: "sandboxRouterAbi", path: join(outDir, "IMSYSandboxRouter.sol", "IMSYSandboxRouter.json") },
  { name: "sandboxTokenAbi", path: join(outDir, "SandboxToken.sol", "SandboxToken.json") },
]

const exports = []
for (const target of targets) {
  const artifact = JSON.parse(readFileSync(target.path, "utf8"))
  const abi = artifact.abi
  if (!Array.isArray(abi)) throw new Error(`No ABI in ${target.path}`)
  exports.push(`export const ${target.name} = ${JSON.stringify(abi, null, 2)} as const`)
}

const dest = join(here, "..", "lib", "web3", "abis.ts")
mkdirSync(dirname(dest), { recursive: true })
writeFileSync(
  dest,
  ["// Auto-generated by client/scripts/extract-abis.mjs — do not edit by hand.", "", ...exports].join("\n") +
    "\n",
)
console.log(`abis.ts written: ${dest}`)
